#!/bin/bash

# NOTE:
#       COVERAGE ANALYSIS IS ONLY AVAILABLE
#       IF THE SIMULATION REGRESSION (i.e. run_all script)
#       WAS RUN USING "ncverilog" SIMULATOR

# Remove old merged report
rm -rf cov_work/design/merged_coverage

# Merge all available coverage reports
iccr ../bin/cov_iccr_merge.cf

# Launch GUI
iccr -test cov_work/design/merged_coverage -GUI
